In [1]:
import numpy as np

In [2]:
january = np.array([-2,  5, -5,  6, -2,  0,  6,  2,  8,  0,  6, -1,  3,  3,  7,  0, -5,
        7,  4,  7,  8, -1,  5, -2,  3, -3, -2,  7,  8,  4,  2])

Donnez toutes les températures qui sont supérieures à 0.

In [3]:
mask_sup_zero = january > 0
january[mask_sup_zero]

array([5, 6, 6, 2, 8, 6, 3, 3, 7, 7, 4, 7, 8, 5, 3, 7, 8, 4, 2])

Comparez les températures supérieures et inférieures à 0.

In [4]:
comp = (january > 0).sum() > (january < 0).sum()

In [12]:
info = "plus" if comp else "moins"

In [13]:
print(f"Il y a {info} de températures positives que de températures négatives")

Il y a plus de températures positives que de températures négatives


Donnez le pourcentage des températures positives sur le mois.

In [18]:
per_t_positive = round( (january > 0).sum() / len(january), 2 ) * 100

In [22]:
print(f"Température {per_t_positive} %")

Température 61.0 %


Créez un tableau days pour les jours du mois et donnez les jours pour lesquels la température était supérieure à 0.

In [25]:
days = np.arange( 1, len(january) + 1 )

In [27]:
days[ january > 0 ]

array([ 2,  4,  7,  8,  9, 11, 13, 14, 15, 18, 19, 20, 21, 23, 25, 28, 29,
       30, 31])

5. Donnez toutes les températures supérieures à 0 à partir du dixième jour du mois.

In [31]:
january[9:][january[9:] > 0]

array([6, 3, 3, 7, 7, 4, 7, 8, 5, 3, 7, 8, 4, 2])

In [45]:
for d, t in zip(days[9:][january[9:] > 0], january[9:][january[9:] > 0]):
    print(f"day: {d} temperature: {t}")

day: 11 temperature: 6
day: 13 temperature: 3
day: 14 temperature: 3
day: 15 temperature: 7
day: 18 temperature: 7
day: 19 temperature: 4
day: 20 temperature: 7
day: 21 temperature: 8
day: 23 temperature: 5
day: 25 temperature: 3
day: 28 temperature: 7
day: 29 temperature: 8
day: 30 temperature: 4
day: 31 temperature: 2


In [49]:
m = np.median(january)

In [50]:
january[january < 0] = m

january

array([3, 5, 3, 6, 3, 0, 6, 2, 8, 0, 6, 3, 3, 3, 7, 0, 3, 7, 4, 7, 8, 3,
       5, 3, 3, 3, 3, 7, 8, 4, 2])