In [1]:
import numpy as np  # alias de Numpy

In [3]:
#help(np)

In [8]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

print(a)          # [1 2 3]
print(a.shape)    # (3,)

[1 2 3]
(3,)


In [9]:
2*a + b 

array([3, 6, 9])

In [10]:
a*b

array([1, 4, 9])

In [11]:
c = np.array([[1,2], [3,2] ])

In [12]:
c.shape

(2, 2)

In [32]:
a = np.random.randint(0, 1_000, size=100)

In [33]:
(a < 500).sum()

np.int64(52)

In [34]:
a.mean()

np.float64(460.59)

In [36]:
a[ a > 500 ] 

array([645, 678, 962, 543, 652, 921, 692, 973, 785, 861, 704, 916, 665,
       669, 966, 641, 677, 973, 633, 529, 937, 573, 641, 570, 678, 821,
       764, 748, 981, 504, 578, 910, 758, 532, 882, 516, 965, 902, 562,
       541, 711, 599, 674, 891, 801, 754, 556, 608])